---
title: "Data Base - CRNL Stat Scripts"
date: "`r Sys.Date()`"
output:
  rmdformats::material:
    highlight: kate
---

Welcome to the CRNL's statistic data-base.   

# Scripts published

## 2021

> Ramalho B. L., Moly J., Raffin E., Bouet R., Harquel S., Farnè A., Reilly K.T. (2021) Electrocutaneous stimulation to the face inhibits motor evoked potentials in the hand: Face-hand sensorimotor interactions revealed by afferent inhibition. EJN   

key-words:   
GLMMER, time series, power, bayesian

Paper published : [here](https://pubmed.ncbi.nlm.nih.gov/34796553/)   
html script: [here](Scripts/2021/Ramalho_al_2021.html)    
Markdown script : [here](Scripts/2021/Ramalho_al_2021.Rmd)    

***

> Ramalho B. L., Moly J., Raffin E., Bouet R., Harquel S., Farnè A., Reilly K.T. (2021) Electrocutaneous stimulation to the face inhibits motor evoked potentials in the hand: Face-hand sensorimotor interactions revealed by afferent inhibition. EJN   


key-words:   
GLMMER, time series, power, bayesian

Paper published : [here](https://pubmed.ncbi.nlm.nih.gov/34796553/)   
html script: [here](Scripts/2021/Ramalho_al_2021.html)    
Markdown script : [here](Scripts/2021/Ramalho_al_2021.Rmd)    

## 2022

> Ramalho B. L., Moly J., Raffin E., Bouet R., Harquel S., Farnè A., Reilly K.T. (2021) Electrocutaneous stimulation to the face inhibits motor evoked potentials in the hand: Face-hand sensorimotor interactions revealed by afferent inhibition. EJN   

key-words:   
GLMMER, time series, power, bayesian

Paper published : [here](https://pubmed.ncbi.nlm.nih.gov/34796553/)   
html script: [here](Scripts/2021/Ramalho_al_2021.html)    
Markdown script : [here](Scripts/2021/Ramalho_al_2021.Rmd)    




# Tutos

## GLMM

Formation donnée par O. Abdoun  et R. Bouet en 2021 dans le cadre du "Club Méthodo" du CRNL.   

On retrouve dans ce support:   
- Les bases thérorique des statistiques multivariées basées sur la modélisation linéaire mixte généralisée (GLMM).   
- La syntaxe de modèles (effet fixe, effet aléatoire).   
- Les diagnostiques.    
- Les tests sur les parmètres du modèle.    
- L'exploration des tests post-hoc.   
- Des conseilles de debuggage.   

Le support de la formation se trouve  [ici](Formations/GLMM/MixedModel.html).   
Pour télécharger le document markdown c'est [ici](Formations/GLMM/MixedModel.html).   

## STAN GLMM

Ce support est en constuction. Ce sont plutôt des notes mises au propre.   

STAN est un package proposant une syntaxe ultra simple similaire à celle des modèles GLMM. Ceci permet à ceux qui maîtrise les GLMM de transposer directement dans une stimation Bayesienne des paramètres.    

On retrouve dans ce support:   
- La syntaxe de modèles (effet fixe, effet aléatoire).   
- L'exploration des la qualité des modèles.    
- la description des différentes métriques que propose le Bayesien.   
- Les tests sur les parmètres du modèle.    
- L'exploration des tests post-hoc.   

Le support se trouve  [ici](Formations/GLMM_Stan/STAN_GLMM.html).   
Pour télécharger le document markdown c'est [ici](Formations/GLMM_Stan/STAN_GLMM.Rmd).   


## Configuration RStudio-GITHUB

Ce support est un petit tuto pour configurer RStudio afin qu'il communique avec un compte GITHUB.   

